services:
  camera-service:
    profiles:
      - camera
    build:
      context: .
      dockerfile: ./camera-service/Dockerfile
    restart: unless-stopped
    container_name: alku-camera
    volumes:
      - common:/common:ro
      - data:/data
      - ./camera-service/app:/camera
    env_file:
      - .env
    # Переопределение переменной redis_host из-за network_mode: host
    environment:
      - REDIS_HOST=localhost
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/camera/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      - redis

  streaming-service:
    build:
      context: .
      dockerfile: ./streaming-service/Dockerfile
    restart: unless-stopped
    networks:
      - alku-network
    container_name: alku-streaming
    volumes:
      - common:/common:ro
      - data:/data
      - ./streaming-service/app:/streaming
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      - redis
  
  webui-service:
    build:
      context: .
      dockerfile: ./webui-service/Dockerfile
    restart: unless-stopped
    networks:
      - alku-network
    container_name: alku-webui
    volumes:
      - common:/common:ro
      - data:/data
      - ./webui-service/app:/webui
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  rs013n-service:
    build:  
      context: .
      dockerfile: ./rs013n-service/Dockerfile
    restart: unless-stopped
    networks:
      - alku-network
    container_name: alku-rs013n
    volumes:
      - common:/common:ro
      - data:/data
      - ./rs013n-service/app:/rs013n
    env_file:
      - .env
    ports:
      - "9013:9013"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  rs007l-service:
    build:
      context: .
      dockerfile: ./rs007l-service/Dockerfile
    restart: unless-stopped
    networks:
      - alku-network
    container_name: alku-rs007l
    volumes:
      - common:/common:ro
      - data:/data
      - ./rs007l-service/app:/rs007l
    env_file:
      - .env
    ports:
      - "9007:9007"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  cv-service:
    runtime: nvidia
    build:
      context: .
      dockerfile: ./cv-service/Dockerfile
    restart: unless-stopped
    networks:
      - alku-network
    container_name: alku-cv
    volumes:
      - common:/common:ro
      - data:/data
      - ./cv-service/app:/cv
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      - redis

  io-service:
    build:
      context: .
      dockerfile: ./io-service/Dockerfile
    restart: unless-stopped
    networks:
      - alku-network
    container_name: alku-io
    volumes:
      - common:/common:ro
      - data:/data
      - ./io-service/app:/io
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  master-service:
    build:
      context: .
      dockerfile: ./master-service/Dockerfile
    restart: unless-stopped
    networks:
      - alku-network
    container_name: alku-master
    volumes:
      - common:/common:ro
      - data:/data
      - ./master-service/app:/master
    env_file:
      - .env
    environment:
      - DEBUG=True
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:1.29.1
    restart: unless-stopped
    networks:
      - alku-network
    container_name: alku-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - streaming-service

  redis:
    image: redis:8.2.1
    restart: unless-stopped
    networks:
      - alku-network
    container_name: alku-redis
    ports:
      - "6379:6379"

volumes:
  common:
    driver: local
    driver_opts:
      type: none
      device: ./common
      o: bind
  data:
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind

networks:
  alku-network:
    driver: bridge
    